[package]
name = "adapter"
version = "0.1.0"
edition.workspace = true

[dependencies]
shared.workspace = true
kernel.workspace = true
async-trait.workspace = true
sqlx.workspace = true
derive-new.workspace = true
uuid.workspace = true

[package.metadata.cargo-machete]
ignored = ["shared"]
